### ISSUE TITLE
No way to configure?

### ISSUE THREAD

**Issue by matthauck** [AndreasSchaek/TeamcityTracIntegration#1]
I don't see any notes on how to configure this plugin. At the very least, I assume I would need to configure the URL of the trac server and optionally a project path (keeping in mind some trac servers have no sub-projects but are entirely one big project).

I don't see a new entry in the admin "Issue Tracker" section. Maybe it goes in a config file somewhere on the server?

**Comment by AndreasSchaek** [comment]
Hmm let's see what I've done.
I have a clean (standard) installation of TeamCity 9.0.1.
When the server is up and running I open *Administration -> upload plugin zip* and select the zip from my guthub target directory (teamcity_trac_integration.zip).
The file gets uploaded to *Teamcity_data_directory\plugins*.
The server needs a restart. 
(The [Documentation](https://confluence.jetbrains.com/display/TCD9/Installing+Additional+Plugins) tells to stop the server manually copy the plugin and then start the server again )

When the server is up again, the plugin is listed under external plugins.

Can you see the plugin listed in your server instance?

**Comment by matthauck** [comment]
I did restart the server and I do see the plugin in my server instance of available plugins. Perhaps the problem is I haven't upgraded to 9 yet. Been meaning to but haven't gotten around to it yet. 

Maybe after this then the plugin would create an entry in the dropdown box for "Issue Trackers"?

**Comment by AndreasSchaek** [comment]
Please tell me which version do you use and I'll check the plugin with this specific version

**Comment by matthauck** [comment]
i'm on 8.1.4 now. (planning to upgrade to 9 soon...)

**Comment by matthauck** [comment]
FYI. Just upgraded my server to 9.0.1, and it works like a charm. Thanks!

**Comment by AndreasSchaek** [comment]
Thanks for your message,
I tested 8.1.4 and there was a constructor missing.
The plugin will work now with both Teamcity versions
